name: chand
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.1.0
  logger: ^2.0.2
  window_size: ^0.1.0
  reorderables: ^0.6.0
  home_widget: ^0.8.0
  workmanager: ^0.9.0+3
  foundation: ^0.0.5
  flutter_launcher_icons: ^0.14.4
  shamsi_date: ^1.1.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/default.png
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazirmatn-FD-Medium.ttf
